
[package]
edition = "2021"
name = "hello"
version = "0.1.0"
description = ""
license = "MIT"

[lib]
crate-type = ["cdylib"]

[dependencies]
anyhow = "1.0.82"
extism-pdk = "1.1.0"
fluentci-pdk = "0.1.9"
