/**
 * This code was generated by Builder.io.
 */
import { component$ } from "@builder.io/qwik";

interface AttendeeListProps {
  attendees: number;
}

export const AttendeeList = component$((props: AttendeeListProps) => {
  return (
    <div class="mt-2.5 flex w-full items-center justify-between gap-1.5 whitespace-nowrap rounded-[48px] text-center shadow-sm">
      <div class="flex items-start self-stretch text-sm font-medium leading-none tracking-normal text-white">
        <div class="flex items-center justify-center gap-0.5 overflow-hidden rounded-[999px] bg-black px-2 py-2">
          <button class="gap-2   self-stretch px-1">Join?</button>
        </div>
      </div>
      <div class="flex items-center gap-1.5 self-stretch text-xs leading-none text-blue-950">
        <div class="">+{props.attendees}</div>
        <img
          loading="lazy"
          src="https://cdn.builder.io/api/v1/image/assets/TEMP/d60fbae89c1e1d3aba6909bbab84537127eff4f29faa651afcfdb25c70c3dc29?placeholderIfAbsent=true&apiKey=17e6b1f5aff14ccdbcafd5a66c4951ca"
          class="aspect-[2.8] w-14 shrink-0 object-contain"
          alt="Attendee avatars"
        />
      </div>
    </div>
  );
});
