/**
 * This code was generated by Builder.io.
 */
import { component$ } from '@builder.io/qwik'

interface AttendeeListProps {
  attendees: number
  images: string[]
  link: string
}
export const AttendeeList = component$((props: AttendeeListProps) => {
  return (
    <div class=" flex w-full items-center justify-between gap-1.5 whitespace-nowrap rounded-[48px] text-center ">
      <div class="items-top flex gap-1.5 self-stretch text-xs leading-none text-blue-950">
        {props.images.map((member, index) => (
          <div
            key={index}
            class={`relative h-8 w-8 overflow-hidden rounded-full border-2 border-white ${index > 0 ? '-ml-4' : ''}`}
          >
            <img
              src="https://images.nightcafe.studio/jobs/032KbO9u2g23uM4b102q/032KbO9u2g23uM4b102q--1--5ukpj.jpg?tr=w-640,c-at_max"
              height={64}
              width={64}
            />
          </div>
        ))}
      </div>
    </div>
  )
})
