/**
 * This code was generated by Builder.io.
 */
import { component$ } from "@builder.io/qwik";

interface AttendeeListProps {
  attendees: number;
}

export const AttendeeList = component$((props: AttendeeListProps) => {
  return (
    <div class="flex gap-1.5 items-center mt-2.5 w-full text-center whitespace-nowrap shadow-sm rounded-[48px]">
      <div class="flex items-start self-stretch my-auto text-sm font-medium tracking-normal leading-none text-gray-600">
        <div class="flex overflow-hidden gap-0.5 justify-center items-center px-2 py-1.5 bg-slate-50 rounded-[999px]">
          <div class="gap-2 self-stretch px-1 my-auto">Going</div>
        </div>
      </div>
      <div class="flex flex-1 shrink gap-1.5 items-center self-stretch my-auto text-xs leading-none basis-0 text-blue-950">
        <img
          loading="lazy"
          src="https://cdn.builder.io/api/v1/image/assets/TEMP/d60fbae89c1e1d3aba6909bbab84537127eff4f29faa651afcfdb25c70c3dc29?placeholderIfAbsent=true&apiKey=17e6b1f5aff14ccdbcafd5a66c4951ca"
          class="object-contain shrink-0 gap-0 self-stretch my-auto w-14 aspect-[2.8]"
          alt="Attendee avatars"
        />
        <div class="self-stretch my-auto">+{props.attendees}</div>
      </div>
    </div>
  );
});
