/**
 * This code was generated by Builder.io.
 */
import { component$ } from "@builder.io/qwik";

interface TagProps {
  text: string;
}

export const Tag = component$((props: TagProps) => {
  return (
    <div class="text-md self-stretch overflow-hidden whitespace-nowrap rounded-[999px] bg-slate-50 px-4 py-2">
      {props.text}
    </div>
  );
});
