/**
 * This code was generated by Builder.io.
 */
import { component$ } from "@qwik.dev/core";

import { Link } from "@qwik.dev/router";
interface AttendeeListProps {
  attendees: number;
  images: string[];
  link: string;
}
export const AttendeeList = component$((props: AttendeeListProps) => {
  return (
    <div class="mt-2.5 flex w-full items-center justify-between gap-1.5 whitespace-nowrap rounded-[48px] text-center shadow-sm">
      <div class="flex items-start self-stretch text-sm font-medium leading-none tracking-normal text-white">
        <div class="flex items-center justify-center gap-0.5 overflow-hidden rounded-[999px] bg-black px-2 py-2">
          <Link href={props.link} class="gap-2   self-stretch px-1">
            Join?
          </Link>
        </div>
      </div>
      <div class="flex items-center gap-1.5 self-stretch text-xs leading-none text-blue-950">
        <div class="">+{props.attendees}</div>
        {props.images.map((member, index) => (
          <div
            key={index}
            class={`relative h-8 w-8 overflow-hidden rounded-full border-2 border-white ${index > 0 ? "-ml-4" : ""}`}
          >
            <img
              src="https://images.nightcafe.studio/jobs/032KbO9u2g23uM4b102q/032KbO9u2g23uM4b102q--1--5ukpj.jpg?tr=w-640,c-at_max"
              height={64}
              width={64}
            />
          </div>
        ))}
      </div>
    </div>
  );
});
