/**
 * This code was generated by Builder.io.
 */
import { component$ } from "@builder.io/qwik";

interface TagProps {
  text: string;
}

export const Tag = component$((props: TagProps) => {
  return (
    <div class="overflow-hidden self-stretch px-2 py-0.5 whitespace-nowrap bg-slate-50 rounded-[999px]">
      {props.text}
    </div>
  );
});
