/**
 * This code was generated by Builder.io.
 */
import { component$ } from "@qwik.dev/core";

interface TagProps {
  text: string;
}

export const Tag = component$((props: TagProps) => {
  return (
    <div class="self-stretch overflow-hidden whitespace-nowrap rounded-[999px] bg-slate-50 px-2 py-0.5">
      {props.text}
    </div>
  );
});
