/**
 * This code was generated by Builder.io.
 */
import { component$ } from '@builder.io/qwik'

interface TagProps {
  text: string
}
export const Tag = component$((props: TagProps) => {
  return (
    <span class="inline-flex items-center whitespace-nowrap rounded-full bg-gray-100 px-3 py-1 text-sm font-medium text-gray-800 transition-colors duration-300 hover:bg-gray-200">
      {props.text}
    </span>
  )
})
